services:
  api:
    build: ./api
    container_name: api-php
    volumes:
      - ./api:/var/www/html
    ports:
      - "3000:80"
    networks:
      - app_net
    depends_on:
      - db

  frontend:
    image: php:8.2-apache
    container_name: frontend
    volumes:
      - ./frontend:/var/www/html
    ports:
      - "3001:80"
    networks:
      - app_net
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appdb
      MYSQL_USER: user
      MYSQL_PASSWORD: user123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
    networks:
      - app_net

volumes:
  db_data:

networks:
  app_net:
